import React from 'react'
import mail from '../../src/assets/mail_icon.svg'
import phone from '../../src/assets/call_icon.svg'
import location from '../../src/assets/location_icon.svg'
import instgram from '../../src/assets/insta.png'


const Contact = () => {
    const onSubmit = async (event) => {  //this code is integrated by web3forms
        event.preventDefault();
        const formData = new FormData(event.target);
    
        formData.append("access_key", "c19e3dd4-ff3e-4480-a2c5-cd1040093f11"); //this unique code is generated by web3forms
    
        const object = Object.fromEntries(formData);
        const json = JSON.stringify(object);
    
        const res = await fetch("https://api.web3forms.com/submit", {
          method: "POST",
          headers: {
            "Content-Type": "application/json",
            Accept: "application/json"
          },
          body: json
        }).then((res) => res.json());
    
        if (res.success) {
        alert(res.message);
        event.target.reset();
        }
      };

    return (
        <div id="contact" className="mt-5 py-5" style={{ backgroundColor: '#737171', color: 'black' }}>
            <h1 className="text-center">Get in touch</h1>
            <div className="d-sm-flex gap-5 m-4 justify-content-around ">
                <div className='d-flex flex-column w-sm-50 gap-2'>
                    <h1 className='text-center text-light'>Let's talk</h1>
                    <p>Open to exciting opportunities — ready to contribute and grow in a dynamic team or project.</p>
                    <div className="email text-black text-dark d-flex ">
                        <img src={mail} alt="" className="" />
                        <a className="text-black text-decoration-none btn" href="mailto:rajukushwaha210361@gmail.com">rajukushwaha210361@gmail.com</a>
                    </div>
                    <div className="phone">
                        <img src={phone} alt="" className="t" />
                        <a href="tel:+916386478591" className="text-black text-decoration-none btn">
                            6386478591
                        </a>
                    </div>
                    <div className="location d-flex justify-content-start gap-2 ">
                        <img src={instgram} alt="" className="bg-white" style={{ width: '40px' }} />
                        <a className="text-black text-decoration-none btn" href="https://www.instagram.com/mr_rajukushwaha/">mr_rajukushwaha</a>
                    </div>
                    <div className="location d-flex justify-content-start gap-2 ">
                        
                        <img src={location} alt="" className="" style={{ width: '20px' }} />
                        <p>Lucknow ,India</p>
                    </div>
                </div>
                <div className='d-flex flex-column '>
                    <form onSubmit={onSubmit} className="d-flex flex-column gap-3">
                        <div>
                            <label className='form-lable'>Name</label>
                            <input type="text" name="name" className="form-control" placeholder='Enter your email' required />
                        </div>
                        <div>
                            <label className='form-lable'>Email</label>
                            <input type="email" name="email" className="form-control" placeholder='Enter your email' required />
                        </div>
                        <div>

                            <label className='form-lable'>Write your message here</label>
                            <textarea name="message" cols="30" rows="4" className="form-control" required></textarea>
                        </div>
                        <button className="btn btn-success">Submit</button>
                    </form>
                </div>
            </div>
            <hr/>
            <div>

            </div>
        </div>
    )
}

export default Contact
